run_name: "hope) +features +ncirs +lr +wassLoss +penalty" 
debug: False
device: "cuda:0"
image_size: [28, 28]
random_state: 43
epochs: 20
log_every_n_steps: 2
path_to_mnist: "mnist.csv"
path_to_autoencoder: "weights/autoencoder-epoch=96_epoch-Loss=0.0065_loss.ckpt"
    
n_qubits: 10
n_circuits: 6
generator_dropout: 0.0

alpha: 10
step_disc_every_n_steps: 1
batch_size: 128
optimizers:
  generator:
    type: Adam
    parameters:
      lr: 0.001
      betas: [0.5, 0.999]
  discriminator:
    type: Adam
    parameters:
      lr: 0.001
      betas: [0.5, 0.999]

discriminator:
  type: Sequential
  layers:
    - type: BatchNorm1d
      num_features: 20
    - type: Linear
      in_features: 20
      out_features: 112
      bias: False
    - type: LeakyReLU
      negative_slope: 0.01
    - type: Dropout
      p: 0.10
    - type: Linear
      in_features: 112
      out_features: 56
      bias: False
    - type: LeakyReLU
      negative_slope: 0.01
    - type: Dropout
      p: 0.10
    - type: Linear
      in_features: 64
      out_features: 1
      bias: False
